export const data = {
  location: {
    name: "Rotterdam",
    region: "South Holland",
    country: "Netherlands",
    lat: 51.9225,
    lon: 4.4792,
    tz_id: "Europe/Amsterdam",
    localtime_epoch: 1746111847,
    localtime: "2025-05-01 17:04",
  },
  current: {
    last_updated_epoch: 1746111600,
    last_updated: "2025-05-01 17:00",
    temp_c: 26.1,
    condition: {
      text: "Sunny",
      code: 1000,
    },
    precip_mm: 0.0,
    humidity: 37,
    cloud: 0,
    feelslike_c: 26.2,
  },
  forecast: {
    forecastday: [
      {
        date: "2025-05-01",
        date_epoch: 1746057600,
        day: {
          avgtemp_c: 19.7,
          totalprecip_mm: 0.0,
          daily_will_it_rain: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
          },
        },
        hour: [
          {
            time_epoch: 1746050400,
            time: "2025-05-01 00:00",
            temp_c: 14.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 14.5,
            windchill_c: 14.5,
            heatindex_c: 14.6,
            dewpoint_c: 10.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746054000,
            time: "2025-05-01 01:00",
            temp_c: 14.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 14.3,
            windchill_c: 14.3,
            heatindex_c: 14.4,
            dewpoint_c: 10.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746057600,
            time: "2025-05-01 02:00",
            temp_c: 14.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 14.0,
            windchill_c: 14.0,
            heatindex_c: 14.1,
            dewpoint_c: 10.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746061200,
            time: "2025-05-01 03:00",
            temp_c: 13.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 13.7,
            windchill_c: 13.7,
            heatindex_c: 13.8,
            dewpoint_c: 10.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746064800,
            time: "2025-05-01 04:00",
            temp_c: 13.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 13.7,
            windchill_c: 13.7,
            heatindex_c: 13.9,
            dewpoint_c: 10.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746068400,
            time: "2025-05-01 05:00",
            temp_c: 13.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 13.4,
            windchill_c: 13.4,
            heatindex_c: 13.5,
            dewpoint_c: 10.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746072000,
            time: "2025-05-01 06:00",
            temp_c: 14.0,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 14.0,
            windchill_c: 14.0,
            heatindex_c: 14.0,
            dewpoint_c: 10.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746075600,
            time: "2025-05-01 07:00",
            temp_c: 16.0,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 16.0,
            windchill_c: 16.0,
            heatindex_c: 16.0,
            dewpoint_c: 11.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746079200,
            time: "2025-05-01 08:00",
            temp_c: 18.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 18.4,
            windchill_c: 18.4,
            heatindex_c: 18.4,
            dewpoint_c: 11.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746082800,
            time: "2025-05-01 09:00",
            temp_c: 20.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 20.4,
            windchill_c: 20.4,
            heatindex_c: 20.4,
            dewpoint_c: 11.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746086400,
            time: "2025-05-01 10:00",
            temp_c: 22.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 24.5,
            windchill_c: 22.1,
            heatindex_c: 24.5,
            dewpoint_c: 11.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746090000,
            time: "2025-05-01 11:00",
            temp_c: 23.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 24.9,
            windchill_c: 23.5,
            heatindex_c: 24.9,
            dewpoint_c: 11.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746093600,
            time: "2025-05-01 12:00",
            temp_c: 24.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 25.3,
            windchill_c: 24.6,
            heatindex_c: 25.3,
            dewpoint_c: 11.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746097200,
            time: "2025-05-01 13:00",
            temp_c: 25.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 25.7,
            windchill_c: 25.5,
            heatindex_c: 25.7,
            dewpoint_c: 11.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746100800,
            time: "2025-05-01 14:00",
            temp_c: 26.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 25.9,
            windchill_c: 26.1,
            heatindex_c: 25.9,
            dewpoint_c: 10.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746104400,
            time: "2025-05-01 15:00",
            temp_c: 26.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 25.9,
            windchill_c: 26.2,
            heatindex_c: 25.9,
            dewpoint_c: 9.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746108000,
            time: "2025-05-01 16:00",
            temp_c: 25.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 25.4,
            windchill_c: 25.3,
            heatindex_c: 25.4,
            dewpoint_c: 9.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746111600,
            time: "2025-05-01 17:00",
            temp_c: 26.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 25.1,
            windchill_c: 24.5,
            heatindex_c: 25.1,
            dewpoint_c: 10.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746115200,
            time: "2025-05-01 18:00",
            temp_c: 24.0,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 25.0,
            windchill_c: 24.1,
            heatindex_c: 25.0,
            dewpoint_c: 11.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746118800,
            time: "2025-05-01 19:00",
            temp_c: 22.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 24.5,
            windchill_c: 22.1,
            heatindex_c: 24.5,
            dewpoint_c: 11.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746122400,
            time: "2025-05-01 20:00",
            temp_c: 19.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 19.8,
            windchill_c: 19.8,
            heatindex_c: 19.8,
            dewpoint_c: 10.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746126000,
            time: "2025-05-01 21:00",
            temp_c: 18.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 18.9,
            windchill_c: 18.9,
            heatindex_c: 18.9,
            dewpoint_c: 9.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746129600,
            time: "2025-05-01 22:00",
            temp_c: 18.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 18.5,
            windchill_c: 18.5,
            heatindex_c: 18.5,
            dewpoint_c: 9.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746133200,
            time: "2025-05-01 23:00",
            temp_c: 18.3,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 18.3,
            windchill_c: 18.3,
            heatindex_c: 18.3,
            dewpoint_c: 9.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
        ],
      },
      {
        date: "2025-05-02",
        date_epoch: 1746144000,
        day: {
          avgtemp_c: 18.3,
          totalprecip_mm: 0.37,
          daily_will_it_rain: 1,
          condition: {
            text: "Patchy rain nearby",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
          },
        },
        hour: [
          {
            time_epoch: 1746136800,
            time: "2025-05-02 00:00",
            temp_c: 18.5,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            feelslike_c: 18.5,
            windchill_c: 18.5,
            heatindex_c: 18.5,
            dewpoint_c: 10.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746140400,
            time: "2025-05-02 01:00",
            temp_c: 17.6,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            feelslike_c: 17.6,
            windchill_c: 17.6,
            heatindex_c: 17.6,
            dewpoint_c: 10.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746144000,
            time: "2025-05-02 02:00",
            temp_c: 17.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 17.5,
            windchill_c: 17.5,
            heatindex_c: 17.5,
            dewpoint_c: 10.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746147600,
            time: "2025-05-02 03:00",
            temp_c: 16.8,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            feelslike_c: 16.8,
            windchill_c: 16.8,
            heatindex_c: 16.8,
            dewpoint_c: 10.6,
            will_it_rain: 1,
            chance_of_rain: 87,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746151200,
            time: "2025-05-02 04:00",
            temp_c: 16.0,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            feelslike_c: 16.0,
            windchill_c: 16.0,
            heatindex_c: 16.0,
            dewpoint_c: 11.9,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746154800,
            time: "2025-05-02 05:00",
            temp_c: 15.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 15.9,
            windchill_c: 15.9,
            heatindex_c: 15.9,
            dewpoint_c: 12.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746158400,
            time: "2025-05-02 06:00",
            temp_c: 16.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 16.1,
            windchill_c: 16.1,
            heatindex_c: 16.1,
            dewpoint_c: 13.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746162000,
            time: "2025-05-02 07:00",
            temp_c: 17.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 17.3,
            windchill_c: 17.3,
            heatindex_c: 17.3,
            dewpoint_c: 13.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746165600,
            time: "2025-05-02 08:00",
            temp_c: 19.0,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            feelslike_c: 19.0,
            windchill_c: 19.0,
            heatindex_c: 19.0,
            dewpoint_c: 12.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746169200,
            time: "2025-05-02 09:00",
            temp_c: 20.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 20.2,
            windchill_c: 20.2,
            heatindex_c: 20.2,
            dewpoint_c: 12.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746172800,
            time: "2025-05-02 10:00",
            temp_c: 21.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 21.2,
            windchill_c: 21.2,
            heatindex_c: 24.4,
            dewpoint_c: 11.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746176400,
            time: "2025-05-02 11:00",
            temp_c: 22.0,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 22.0,
            windchill_c: 22.0,
            heatindex_c: 24.5,
            dewpoint_c: 11.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746180000,
            time: "2025-05-02 12:00",
            temp_c: 22.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 24.5,
            windchill_c: 22.4,
            heatindex_c: 24.5,
            dewpoint_c: 11.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746183600,
            time: "2025-05-02 13:00",
            temp_c: 22.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 24.5,
            windchill_c: 22.3,
            heatindex_c: 24.5,
            dewpoint_c: 11.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746187200,
            time: "2025-05-02 14:00",
            temp_c: 22.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 24.4,
            windchill_c: 22.2,
            heatindex_c: 24.4,
            dewpoint_c: 11.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746190800,
            time: "2025-05-02 15:00",
            temp_c: 21.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 21.7,
            windchill_c: 21.7,
            heatindex_c: 24.4,
            dewpoint_c: 11.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746194400,
            time: "2025-05-02 16:00",
            temp_c: 20.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 20.9,
            windchill_c: 20.9,
            heatindex_c: 20.9,
            dewpoint_c: 11.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746198000,
            time: "2025-05-02 17:00",
            temp_c: 19.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 19.9,
            windchill_c: 19.9,
            heatindex_c: 19.9,
            dewpoint_c: 10.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746201600,
            time: "2025-05-02 18:00",
            temp_c: 18.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 18.8,
            windchill_c: 18.8,
            heatindex_c: 18.8,
            dewpoint_c: 10.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746205200,
            time: "2025-05-02 19:00",
            temp_c: 17.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 17.3,
            windchill_c: 17.3,
            heatindex_c: 17.3,
            dewpoint_c: 10.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746208800,
            time: "2025-05-02 20:00",
            temp_c: 15.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 15.5,
            windchill_c: 15.5,
            heatindex_c: 15.5,
            dewpoint_c: 9.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746212400,
            time: "2025-05-02 21:00",
            temp_c: 14.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            feelslike_c: 14.1,
            windchill_c: 14.1,
            heatindex_c: 14.7,
            dewpoint_c: 9.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746216000,
            time: "2025-05-02 22:00",
            temp_c: 13.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 13.0,
            windchill_c: 13.0,
            heatindex_c: 13.7,
            dewpoint_c: 8.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1746219600,
            time: "2025-05-02 23:00",
            temp_c: 12.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            feelslike_c: 11.8,
            windchill_c: 11.8,
            heatindex_c: 12.8,
            dewpoint_c: 8.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
        ],
      },
    ],
  },
};
