export const data = {
  location: {
    name: "Rotterdam",
    region: "South Holland",
    country: "Netherlands",
    lat: 51.9225,
    lon: 4.4792,
    tz_id: "Europe/Amsterdam",
    localtime_epoch: 1745697484,
    localtime: "2025-04-26 21:58",
  },
  current: {
    last_updated_epoch: 1745696700,
    last_updated: "2025-04-26 21:45",
    temp_c: 13.3,
    temp_f: 55.9,
    is_day: 0,
    condition: {
      text: "Clear",
      icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
      code: 1000,
    },
    wind_mph: 6.5,
    wind_kph: 10.4,
    wind_degree: 50,
    wind_dir: "NE",
    pressure_mb: 1022.0,
    pressure_in: 30.18,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 72,
    cloud: 0,
    feelslike_c: 12.5,
    feelslike_f: 54.5,
    windchill_c: 12.0,
    windchill_f: 53.6,
    heatindex_c: 12.9,
    heatindex_f: 55.2,
    dewpoint_c: 7.0,
    dewpoint_f: 44.6,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 0.0,
    gust_mph: 13.4,
    gust_kph: 21.6,
  },
  forecast: {
    forecastday: [
      {
        date: "2025-04-26",
        date_epoch: 1745625600,
        day: {
          maxtemp_c: 18.6,
          maxtemp_f: 65.6,
          mintemp_c: 6.6,
          mintemp_f: 43.8,
          avgtemp_c: 12.9,
          avgtemp_f: 55.2,
          maxwind_mph: 10.1,
          maxwind_kph: 16.2,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 67,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 1.5,
        },
        astro: {
          sunrise: "06:22 AM",
          sunset: "08:59 PM",
          moonrise: "05:37 AM",
          moonset: "07:31 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: 5,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1745618400,
            time: "2025-04-26 00:00",
            temp_c: 8.1,
            temp_f: 46.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 53,
            wind_dir: "NE",
            pressure_mb: 1023.0,
            pressure_in: 30.21,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 87,
            cloud: 9,
            feelslike_c: 6.8,
            feelslike_f: 44.2,
            windchill_c: 6.8,
            windchill_f: 44.2,
            heatindex_c: 8.1,
            heatindex_f: 46.6,
            dewpoint_c: 6.1,
            dewpoint_f: 42.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.8,
            gust_kph: 15.7,
            uv: 0,
          },
          {
            time_epoch: 1745622000,
            time: "2025-04-26 01:00",
            temp_c: 7.8,
            temp_f: 46.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 54,
            wind_dir: "NE",
            pressure_mb: 1023.0,
            pressure_in: 30.21,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 88,
            cloud: 3,
            feelslike_c: 6.4,
            feelslike_f: 43.5,
            windchill_c: 6.4,
            windchill_f: 43.5,
            heatindex_c: 7.8,
            heatindex_f: 46.1,
            dewpoint_c: 6.0,
            dewpoint_f: 42.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.3,
            gust_kph: 16.5,
            uv: 0,
          },
          {
            time_epoch: 1745625600,
            time: "2025-04-26 02:00",
            temp_c: 7.4,
            temp_f: 45.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 56,
            wind_dir: "ENE",
            pressure_mb: 1023.0,
            pressure_in: 30.2,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 89,
            cloud: 5,
            feelslike_c: 5.9,
            feelslike_f: 42.5,
            windchill_c: 5.9,
            windchill_f: 42.5,
            heatindex_c: 7.4,
            heatindex_f: 45.4,
            dewpoint_c: 5.8,
            dewpoint_f: 42.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.8,
            gust_kph: 17.4,
            uv: 0,
          },
          {
            time_epoch: 1745629200,
            time: "2025-04-26 03:00",
            temp_c: 7.1,
            temp_f: 44.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 57,
            wind_dir: "ENE",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 90,
            cloud: 16,
            feelslike_c: 5.5,
            feelslike_f: 41.8,
            windchill_c: 5.5,
            windchill_f: 41.8,
            heatindex_c: 7.1,
            heatindex_f: 44.8,
            dewpoint_c: 5.6,
            dewpoint_f: 42.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.0,
            gust_kph: 17.7,
            uv: 0,
          },
          {
            time_epoch: 1745632800,
            time: "2025-04-26 04:00",
            temp_c: 6.7,
            temp_f: 44.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 58,
            wind_dir: "ENE",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 93,
            cloud: 6,
            feelslike_c: 4.9,
            feelslike_f: 40.9,
            windchill_c: 4.9,
            windchill_f: 40.9,
            heatindex_c: 6.7,
            heatindex_f: 44.1,
            dewpoint_c: 5.7,
            dewpoint_f: 42.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.3,
            gust_kph: 18.3,
            uv: 0,
          },
          {
            time_epoch: 1745636400,
            time: "2025-04-26 05:00",
            temp_c: 6.6,
            temp_f: 43.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 57,
            wind_dir: "ENE",
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 92,
            cloud: 2,
            feelslike_c: 4.8,
            feelslike_f: 40.7,
            windchill_c: 4.8,
            windchill_f: 40.7,
            heatindex_c: 6.6,
            heatindex_f: 43.8,
            dewpoint_c: 5.4,
            dewpoint_f: 41.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.3,
            gust_kph: 18.1,
            uv: 0,
          },
          {
            time_epoch: 1745640000,
            time: "2025-04-26 06:00",
            temp_c: 6.9,
            temp_f: 44.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 56,
            wind_dir: "ENE",
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 91,
            cloud: 0,
            feelslike_c: 5.2,
            feelslike_f: 41.3,
            windchill_c: 5.2,
            windchill_f: 41.3,
            heatindex_c: 6.9,
            heatindex_f: 44.4,
            dewpoint_c: 5.5,
            dewpoint_f: 41.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.2,
            gust_kph: 18.1,
            uv: 0,
          },
          {
            time_epoch: 1745643600,
            time: "2025-04-26 07:00",
            temp_c: 8.9,
            temp_f: 48.0,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 66,
            wind_dir: "ENE",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 83,
            cloud: 1,
            feelslike_c: 7.6,
            feelslike_f: 45.7,
            windchill_c: 7.6,
            windchill_f: 45.7,
            heatindex_c: 8.9,
            heatindex_f: 48.0,
            dewpoint_c: 6.2,
            dewpoint_f: 43.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 0.0,
          },
          {
            time_epoch: 1745647200,
            time: "2025-04-26 08:00",
            temp_c: 11.3,
            temp_f: 52.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 74,
            wind_dir: "ENE",
            pressure_mb: 1023.0,
            pressure_in: 30.2,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 73,
            cloud: 4,
            feelslike_c: 10.2,
            feelslike_f: 50.4,
            windchill_c: 10.2,
            windchill_f: 50.4,
            heatindex_c: 11.3,
            heatindex_f: 52.4,
            dewpoint_c: 6.6,
            dewpoint_f: 43.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.2,
            gust_kph: 13.2,
            uv: 0.4,
          },
          {
            time_epoch: 1745650800,
            time: "2025-04-26 09:00",
            temp_c: 13.5,
            temp_f: 56.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 77,
            wind_dir: "ENE",
            pressure_mb: 1023.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 63,
            cloud: 10,
            feelslike_c: 12.5,
            feelslike_f: 54.4,
            windchill_c: 12.5,
            windchill_f: 54.4,
            heatindex_c: 13.5,
            heatindex_f: 56.2,
            dewpoint_c: 6.6,
            dewpoint_f: 43.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.3,
            gust_kph: 15.0,
            uv: 1.0,
          },
          {
            time_epoch: 1745654400,
            time: "2025-04-26 10:00",
            temp_c: 15.2,
            temp_f: 59.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 86,
            wind_dir: "E",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 54,
            cloud: 4,
            feelslike_c: 15.2,
            feelslike_f: 59.4,
            windchill_c: 15.2,
            windchill_f: 59.4,
            heatindex_c: 15.2,
            heatindex_f: 59.4,
            dewpoint_c: 6.0,
            dewpoint_f: 42.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.1,
            gust_kph: 17.8,
            uv: 1.9,
          },
          {
            time_epoch: 1745658000,
            time: "2025-04-26 11:00",
            temp_c: 16.3,
            temp_f: 61.4,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 93,
            wind_dir: "E",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 49,
            cloud: 36,
            feelslike_c: 16.3,
            feelslike_f: 61.4,
            windchill_c: 16.3,
            windchill_f: 61.4,
            heatindex_c: 16.3,
            heatindex_f: 61.4,
            dewpoint_c: 5.7,
            dewpoint_f: 42.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.6,
            uv: 3.3,
          },
          {
            time_epoch: 1745661600,
            time: "2025-04-26 12:00",
            temp_c: 17.1,
            temp_f: 62.8,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 95,
            wind_dir: "E",
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 47,
            cloud: 55,
            feelslike_c: 17.1,
            feelslike_f: 62.8,
            windchill_c: 17.1,
            windchill_f: 62.8,
            heatindex_c: 17.1,
            heatindex_f: 62.8,
            dewpoint_c: 5.7,
            dewpoint_f: 42.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.1,
            gust_kph: 17.8,
            uv: 4.5,
          },
          {
            time_epoch: 1745665200,
            time: "2025-04-26 13:00",
            temp_c: 17.8,
            temp_f: 64.1,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 95,
            wind_dir: "E",
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 45,
            cloud: 36,
            feelslike_c: 17.8,
            feelslike_f: 64.1,
            windchill_c: 17.8,
            windchill_f: 64.1,
            heatindex_c: 17.8,
            heatindex_f: 64.1,
            dewpoint_c: 5.8,
            dewpoint_f: 42.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.6,
            gust_kph: 17.0,
            uv: 5.3,
          },
          {
            time_epoch: 1745668800,
            time: "2025-04-26 14:00",
            temp_c: 18.4,
            temp_f: 65.1,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 96,
            wind_dir: "E",
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 44,
            cloud: 30,
            feelslike_c: 18.4,
            feelslike_f: 65.1,
            windchill_c: 18.4,
            windchill_f: 65.1,
            heatindex_c: 18.4,
            heatindex_f: 65.1,
            dewpoint_c: 5.8,
            dewpoint_f: 42.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 5.5,
          },
          {
            time_epoch: 1745672400,
            time: "2025-04-26 15:00",
            temp_c: 18.6,
            temp_f: 65.5,
            is_day: 1,
            condition: {
              text: "Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 98,
            wind_dir: "E",
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 43,
            cloud: 70,
            feelslike_c: 18.6,
            feelslike_f: 65.6,
            windchill_c: 18.6,
            windchill_f: 65.6,
            heatindex_c: 18.6,
            heatindex_f: 65.6,
            dewpoint_c: 5.8,
            dewpoint_f: 42.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.0,
            gust_kph: 16.2,
            uv: 4.9,
          },
          {
            time_epoch: 1745676000,
            time: "2025-04-26 16:00",
            temp_c: 18.6,
            temp_f: 65.6,
            is_day: 1,
            condition: {
              text: "Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 99,
            wind_dir: "E",
            pressure_mb: 1022.0,
            pressure_in: 30.17,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 43,
            cloud: 68,
            feelslike_c: 18.6,
            feelslike_f: 65.6,
            windchill_c: 18.6,
            windchill_f: 65.6,
            heatindex_c: 18.6,
            heatindex_f: 65.6,
            dewpoint_c: 5.9,
            dewpoint_f: 42.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.2,
            gust_kph: 16.4,
            uv: 3.8,
          },
          {
            time_epoch: 1745679600,
            time: "2025-04-26 17:00",
            temp_c: 18.2,
            temp_f: 64.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 99,
            wind_dir: "E",
            pressure_mb: 1022.0,
            pressure_in: 30.17,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 45,
            cloud: 22,
            feelslike_c: 18.2,
            feelslike_f: 64.8,
            windchill_c: 18.2,
            windchill_f: 64.8,
            heatindex_c: 18.2,
            heatindex_f: 64.8,
            dewpoint_c: 6.0,
            dewpoint_f: 42.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.6,
            gust_kph: 17.1,
            uv: 2.5,
          },
          {
            time_epoch: 1745683200,
            time: "2025-04-26 18:00",
            temp_c: 17.6,
            temp_f: 63.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 101,
            wind_dir: "ESE",
            pressure_mb: 1022.0,
            pressure_in: 30.17,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 50,
            cloud: 17,
            feelslike_c: 17.6,
            feelslike_f: 63.6,
            windchill_c: 17.6,
            windchill_f: 63.6,
            heatindex_c: 17.6,
            heatindex_f: 63.6,
            dewpoint_c: 7.1,
            dewpoint_f: 44.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.1,
            gust_kph: 16.3,
            uv: 1.4,
          },
          {
            time_epoch: 1745686800,
            time: "2025-04-26 19:00",
            temp_c: 16.1,
            temp_f: 60.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 91,
            wind_dir: "E",
            pressure_mb: 1022.0,
            pressure_in: 30.17,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 58,
            cloud: 15,
            feelslike_c: 16.1,
            feelslike_f: 60.9,
            windchill_c: 16.1,
            windchill_f: 60.9,
            heatindex_c: 16.1,
            heatindex_f: 60.9,
            dewpoint_c: 7.8,
            dewpoint_f: 46.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.4,
            gust_kph: 16.7,
            uv: 0.6,
          },
          {
            time_epoch: 1745690400,
            time: "2025-04-26 20:00",
            temp_c: 14.1,
            temp_f: 57.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 67,
            wind_dir: "ENE",
            pressure_mb: 1023.0,
            pressure_in: 30.2,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 64,
            cloud: 6,
            feelslike_c: 13.5,
            feelslike_f: 56.2,
            windchill_c: 13.5,
            windchill_f: 56.2,
            heatindex_c: 14.1,
            heatindex_f: 57.4,
            dewpoint_c: 7.3,
            dewpoint_f: 45.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.1,
            gust_kph: 21.1,
            uv: 0.2,
          },
          {
            time_epoch: 1745694000,
            time: "2025-04-26 21:00",
            temp_c: 13.3,
            temp_f: 55.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 50,
            wind_dir: "NE",
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 72,
            cloud: 0,
            feelslike_c: 12.0,
            feelslike_f: 53.6,
            windchill_c: 12.0,
            windchill_f: 53.6,
            heatindex_c: 12.9,
            heatindex_f: 55.2,
            dewpoint_c: 7.0,
            dewpoint_f: 44.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
            uv: 0,
          },
          {
            time_epoch: 1745697600,
            time: "2025-04-26 22:00",
            temp_c: 12.0,
            temp_f: 53.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 53,
            wind_dir: "NE",
            pressure_mb: 1024.0,
            pressure_in: 30.23,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 71,
            cloud: 8,
            feelslike_c: 11.1,
            feelslike_f: 51.9,
            windchill_c: 11.1,
            windchill_f: 51.9,
            heatindex_c: 12.0,
            heatindex_f: 53.6,
            dewpoint_c: 6.8,
            dewpoint_f: 44.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.7,
            gust_kph: 20.4,
            uv: 0,
          },
          {
            time_epoch: 1745701200,
            time: "2025-04-26 23:00",
            temp_c: 11.5,
            temp_f: 52.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 63,
            wind_dir: "ENE",
            pressure_mb: 1024.0,
            pressure_in: 30.23,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 73,
            cloud: 11,
            feelslike_c: 10.6,
            feelslike_f: 51.2,
            windchill_c: 10.6,
            windchill_f: 51.2,
            heatindex_c: 11.5,
            heatindex_f: 52.7,
            dewpoint_c: 6.9,
            dewpoint_f: 44.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.3,
            gust_kph: 18.1,
            uv: 0,
          },
        ],
      },
      {
        date: "2025-04-27",
        date_epoch: 1745712000,
        day: {
          maxtemp_c: 19.4,
          maxtemp_f: 66.9,
          mintemp_c: 8.7,
          mintemp_f: 47.6,
          avgtemp_c: 14.0,
          avgtemp_f: 57.3,
          maxwind_mph: 7.4,
          maxwind_kph: 11.9,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 61,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 1.5,
        },
        astro: {
          sunrise: "06:20 AM",
          sunset: "09:00 PM",
          moonrise: "05:51 AM",
          moonset: "09:06 PM",
          moon_phase: "New Moon",
          moon_illumination: 1,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1745704800,
            time: "2025-04-27 00:00",
            temp_c: 11.0,
            temp_f: 51.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 67,
            wind_dir: "ENE",
            pressure_mb: 1024.0,
            pressure_in: 30.23,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 76,
            cloud: 17,
            feelslike_c: 10.0,
            feelslike_f: 49.9,
            windchill_c: 10.0,
            windchill_f: 49.9,
            heatindex_c: 11.0,
            heatindex_f: 51.8,
            dewpoint_c: 6.9,
            dewpoint_f: 44.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.2,
            gust_kph: 19.7,
            uv: 0,
          },
          {
            time_epoch: 1745708400,
            time: "2025-04-27 01:00",
            temp_c: 10.5,
            temp_f: 50.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 72,
            wind_dir: "ENE",
            pressure_mb: 1024.0,
            pressure_in: 30.23,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 77,
            cloud: 23,
            feelslike_c: 9.3,
            feelslike_f: 48.8,
            windchill_c: 9.3,
            windchill_f: 48.8,
            heatindex_c: 10.5,
            heatindex_f: 50.9,
            dewpoint_c: 6.7,
            dewpoint_f: 44.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.2,
            gust_kph: 19.7,
            uv: 0,
          },
          {
            time_epoch: 1745712000,
            time: "2025-04-27 02:00",
            temp_c: 9.8,
            temp_f: 49.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 80,
            wind_dir: "E",
            pressure_mb: 1023.0,
            pressure_in: 30.22,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 80,
            cloud: 23,
            feelslike_c: 8.6,
            feelslike_f: 47.5,
            windchill_c: 8.6,
            windchill_f: 47.5,
            heatindex_c: 9.8,
            heatindex_f: 49.7,
            dewpoint_c: 6.5,
            dewpoint_f: 43.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.7,
            gust_kph: 18.9,
            uv: 0,
          },
          {
            time_epoch: 1745715600,
            time: "2025-04-27 03:00",
            temp_c: 9.3,
            temp_f: 48.7,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 87,
            wind_dir: "E",
            pressure_mb: 1024.0,
            pressure_in: 30.23,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 82,
            cloud: 26,
            feelslike_c: 8.1,
            feelslike_f: 46.5,
            windchill_c: 8.1,
            windchill_f: 46.5,
            heatindex_c: 9.3,
            heatindex_f: 48.7,
            dewpoint_c: 6.4,
            dewpoint_f: 43.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.3,
            gust_kph: 18.1,
            uv: 0,
          },
          {
            time_epoch: 1745719200,
            time: "2025-04-27 04:00",
            temp_c: 9.0,
            temp_f: 48.2,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 88,
            wind_dir: "E",
            pressure_mb: 1024.0,
            pressure_in: 30.23,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 83,
            cloud: 25,
            feelslike_c: 7.7,
            feelslike_f: 45.9,
            windchill_c: 7.7,
            windchill_f: 45.9,
            heatindex_c: 9.0,
            heatindex_f: 48.2,
            dewpoint_c: 6.3,
            dewpoint_f: 43.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.3,
            gust_kph: 18.1,
            uv: 0,
          },
          {
            time_epoch: 1745722800,
            time: "2025-04-27 05:00",
            temp_c: 8.7,
            temp_f: 47.6,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 87,
            wind_dir: "E",
            pressure_mb: 1024.0,
            pressure_in: 30.24,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 84,
            cloud: 30,
            feelslike_c: 7.3,
            feelslike_f: 45.1,
            windchill_c: 7.3,
            windchill_f: 45.1,
            heatindex_c: 8.7,
            heatindex_f: 47.6,
            dewpoint_c: 6.1,
            dewpoint_f: 43.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.3,
            gust_kph: 18.1,
            uv: 0,
          },
          {
            time_epoch: 1745726400,
            time: "2025-04-27 06:00",
            temp_c: 8.7,
            temp_f: 47.7,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 88,
            wind_dir: "E",
            pressure_mb: 1024.0,
            pressure_in: 30.25,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 83,
            cloud: 53,
            feelslike_c: 7.3,
            feelslike_f: 45.2,
            windchill_c: 7.3,
            windchill_f: 45.2,
            heatindex_c: 8.7,
            heatindex_f: 47.7,
            dewpoint_c: 6.0,
            dewpoint_f: 42.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.0,
            gust_kph: 17.7,
            uv: 0,
          },
          {
            time_epoch: 1745730000,
            time: "2025-04-27 07:00",
            temp_c: 10.4,
            temp_f: 50.7,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 91,
            wind_dir: "E",
            pressure_mb: 1025.0,
            pressure_in: 30.27,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 76,
            cloud: 55,
            feelslike_c: 9.3,
            feelslike_f: 48.8,
            windchill_c: 9.3,
            windchill_f: 48.8,
            heatindex_c: 10.4,
            heatindex_f: 50.7,
            dewpoint_c: 6.4,
            dewpoint_f: 43.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.8,
            gust_kph: 14.1,
            uv: 0.0,
          },
          {
            time_epoch: 1745733600,
            time: "2025-04-27 08:00",
            temp_c: 12.4,
            temp_f: 54.4,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 92,
            wind_dir: "E",
            pressure_mb: 1025.0,
            pressure_in: 30.27,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 67,
            cloud: 29,
            feelslike_c: 11.6,
            feelslike_f: 52.9,
            windchill_c: 11.6,
            windchill_f: 52.9,
            heatindex_c: 12.4,
            heatindex_f: 54.4,
            dewpoint_c: 6.6,
            dewpoint_f: 43.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.7,
            gust_kph: 12.5,
            uv: 0.4,
          },
          {
            time_epoch: 1745737200,
            time: "2025-04-27 09:00",
            temp_c: 14.3,
            temp_f: 57.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 85,
            wind_dir: "E",
            pressure_mb: 1025.0,
            pressure_in: 30.28,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 60,
            cloud: 18,
            feelslike_c: 13.8,
            feelslike_f: 56.9,
            windchill_c: 13.8,
            windchill_f: 56.9,
            heatindex_c: 14.3,
            heatindex_f: 57.7,
            dewpoint_c: 6.7,
            dewpoint_f: 44.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.9,
            gust_kph: 11.1,
            uv: 1.0,
          },
          {
            time_epoch: 1745740800,
            time: "2025-04-27 10:00",
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 80,
            wind_dir: "E",
            pressure_mb: 1025.0,
            pressure_in: 30.28,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 53,
            cloud: 8,
            feelslike_c: 16.0,
            feelslike_f: 60.8,
            windchill_c: 16.0,
            windchill_f: 60.8,
            heatindex_c: 16.0,
            heatindex_f: 60.8,
            dewpoint_c: 6.4,
            dewpoint_f: 43.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.6,
            uv: 2.0,
          },
          {
            time_epoch: 1745744400,
            time: "2025-04-27 11:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 80,
            wind_dir: "E",
            pressure_mb: 1025.0,
            pressure_in: 30.28,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 47,
            cloud: 5,
            feelslike_c: 17.4,
            feelslike_f: 63.4,
            windchill_c: 17.4,
            windchill_f: 63.4,
            heatindex_c: 17.4,
            heatindex_f: 63.4,
            dewpoint_c: 5.9,
            dewpoint_f: 42.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.0,
            gust_kph: 12.9,
            uv: 3.3,
          },
          {
            time_epoch: 1745748000,
            time: "2025-04-27 12:00",
            temp_c: 18.3,
            temp_f: 64.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 81,
            wind_dir: "E",
            pressure_mb: 1025.0,
            pressure_in: 30.27,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 43,
            cloud: 2,
            feelslike_c: 18.3,
            feelslike_f: 64.9,
            windchill_c: 18.3,
            windchill_f: 64.9,
            heatindex_c: 18.3,
            heatindex_f: 64.9,
            dewpoint_c: 5.4,
            dewpoint_f: 41.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 4.4,
          },
          {
            time_epoch: 1745751600,
            time: "2025-04-27 13:00",
            temp_c: 18.9,
            temp_f: 65.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 80,
            wind_dir: "E",
            pressure_mb: 1025.0,
            pressure_in: 30.27,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 41,
            cloud: 5,
            feelslike_c: 18.9,
            feelslike_f: 65.9,
            windchill_c: 18.9,
            windchill_f: 65.9,
            heatindex_c: 18.9,
            heatindex_f: 65.9,
            dewpoint_c: 5.3,
            dewpoint_f: 41.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.7,
            gust_kph: 12.4,
            uv: 5.2,
          },
          {
            time_epoch: 1745755200,
            time: "2025-04-27 14:00",
            temp_c: 19.2,
            temp_f: 66.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 75,
            wind_dir: "ENE",
            pressure_mb: 1025.0,
            pressure_in: 30.27,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 40,
            cloud: 7,
            feelslike_c: 19.2,
            feelslike_f: 66.6,
            windchill_c: 19.2,
            windchill_f: 66.6,
            heatindex_c: 19.2,
            heatindex_f: 66.6,
            dewpoint_c: 5.5,
            dewpoint_f: 41.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.0,
            gust_kph: 11.2,
            uv: 5.3,
          },
          {
            time_epoch: 1745758800,
            time: "2025-04-27 15:00",
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 59,
            wind_dir: "ENE",
            pressure_mb: 1025.0,
            pressure_in: 30.26,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 40,
            cloud: 16,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 5.4,
            dewpoint_f: 41.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.9,
            gust_kph: 9.5,
            uv: 4.8,
          },
          {
            time_epoch: 1745762400,
            time: "2025-04-27 16:00",
            temp_c: 19.4,
            temp_f: 66.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 60,
            wind_dir: "ENE",
            pressure_mb: 1025.0,
            pressure_in: 30.26,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 40,
            cloud: 6,
            feelslike_c: 19.4,
            feelslike_f: 66.8,
            windchill_c: 19.4,
            windchill_f: 66.8,
            heatindex_c: 19.4,
            heatindex_f: 66.8,
            dewpoint_c: 5.4,
            dewpoint_f: 41.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.7,
            gust_kph: 9.2,
            uv: 3.7,
          },
          {
            time_epoch: 1745766000,
            time: "2025-04-27 17:00",
            temp_c: 19.0,
            temp_f: 66.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 58,
            wind_dir: "ENE",
            pressure_mb: 1025.0,
            pressure_in: 30.26,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 41,
            cloud: 4,
            feelslike_c: 19.0,
            feelslike_f: 66.2,
            windchill_c: 19.0,
            windchill_f: 66.2,
            heatindex_c: 19.0,
            heatindex_f: 66.2,
            dewpoint_c: 5.5,
            dewpoint_f: 41.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.3,
            gust_kph: 8.6,
            uv: 2.5,
          },
          {
            time_epoch: 1745769600,
            time: "2025-04-27 18:00",
            temp_c: 18.4,
            temp_f: 65.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 55,
            wind_dir: "NE",
            pressure_mb: 1025.0,
            pressure_in: 30.26,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 45,
            cloud: 6,
            feelslike_c: 18.4,
            feelslike_f: 65.1,
            windchill_c: 18.4,
            windchill_f: 65.1,
            heatindex_c: 18.4,
            heatindex_f: 65.1,
            dewpoint_c: 6.3,
            dewpoint_f: 43.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.9,
            gust_kph: 7.8,
            uv: 1.4,
          },
          {
            time_epoch: 1745773200,
            time: "2025-04-27 19:00",
            temp_c: 16.7,
            temp_f: 62.0,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 83,
            wind_dir: "E",
            pressure_mb: 1025.0,
            pressure_in: 30.27,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 54,
            cloud: 2,
            feelslike_c: 16.7,
            feelslike_f: 62.0,
            windchill_c: 16.7,
            windchill_f: 62.0,
            heatindex_c: 16.7,
            heatindex_f: 62.0,
            dewpoint_c: 7.2,
            dewpoint_f: 45.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.4,
            gust_kph: 10.2,
            uv: 0.6,
          },
          {
            time_epoch: 1745776800,
            time: "2025-04-27 20:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 70,
            wind_dir: "ENE",
            pressure_mb: 1026.0,
            pressure_in: 30.29,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 59,
            cloud: 0,
            feelslike_c: 14.1,
            feelslike_f: 57.4,
            windchill_c: 14.1,
            windchill_f: 57.4,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 6.4,
            dewpoint_f: 43.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 0.2,
          },
          {
            time_epoch: 1745780400,
            time: "2025-04-27 21:00",
            temp_c: 12.9,
            temp_f: 55.3,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 69,
            wind_dir: "ENE",
            pressure_mb: 1026.0,
            pressure_in: 30.31,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 62,
            cloud: 0,
            feelslike_c: 12.4,
            feelslike_f: 54.2,
            windchill_c: 12.4,
            windchill_f: 54.2,
            heatindex_c: 12.9,
            heatindex_f: 55.3,
            dewpoint_c: 5.9,
            dewpoint_f: 42.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.2,
            gust_kph: 18.1,
            uv: 0,
          },
          {
            time_epoch: 1745784000,
            time: "2025-04-27 22:00",
            temp_c: 11.9,
            temp_f: 53.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 70,
            wind_dir: "ENE",
            pressure_mb: 1026.0,
            pressure_in: 30.31,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 65,
            cloud: 0,
            feelslike_c: 11.2,
            feelslike_f: 52.1,
            windchill_c: 11.2,
            windchill_f: 52.1,
            heatindex_c: 11.9,
            heatindex_f: 53.5,
            dewpoint_c: 5.7,
            dewpoint_f: 42.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.3,
            gust_kph: 18.1,
            uv: 0,
          },
          {
            time_epoch: 1745787600,
            time: "2025-04-27 23:00",
            temp_c: 11.2,
            temp_f: 52.2,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 70,
            wind_dir: "ENE",
            pressure_mb: 1026.0,
            pressure_in: 30.31,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 68,
            cloud: 0,
            feelslike_c: 10.6,
            feelslike_f: 51.1,
            windchill_c: 10.6,
            windchill_f: 51.1,
            heatindex_c: 11.2,
            heatindex_f: 52.2,
            dewpoint_c: 5.6,
            dewpoint_f: 42.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 0,
          },
        ],
      },
    ],
  },
};
